spring:
  application:
    name: casa-do-codigo
  datasource:
    url: jdbc:mysql://localhost:3306/casadocodigo?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug